"""Calibration/lens prior groups applied through the RealityScan CLI.

This module replaces the calibration XMP sidecars that used to be written
beside every image (`camera_registry.calibration_xmp` /
`ensure_calibration_sidecars`). The grouping those sidecars carried is now
set in-session with the RealityScan 2.2 commands

    -selectImage <regexp>
    -setPriorCalibrationGroup <n>
    -setPriorLensGroup <n>

so nothing is ever written into the image tree.

WHY THIS EXISTS
---------------
FINDINGS.md recorded "XMP calibration sidecars are the ONLY way to separate
EXIF-identical cameras" (WCA rendered JPGs share one Z CAM E2-F6 model
string and carry no focal tag). That is SUPERSEDED: `-setPriorCalibrationGroup`
and `-setPriorLensGroup` set exactly the same two groups per selection, and
`-selectImage` accepts a regular expression - which is precisely what
`camera_registry` already stores per filename family. Sidecars were never
the only mechanism, only the one this pipeline happened to use.

Removing them retires a cluster of recorded defects at once: the identity
harvest that permanently stripped 17.5% of zone_1's calibration priors and
confounded PD-4/PD-4a; priors silently never loading because they were
written `image.jpg.xmp` when RealityScan reads `image.xmp`; and the ON2026
hygiene collision where the harvest swept hand-placed calibration files it
did not own.

WHAT IS LOST
------------
`Camera.focal_length_35mm` and the per-camera `distortion_model` were
numeric/model priors the XMP could state directly; the two CLI commands set
GROUPING only. Numeric intrinsics come from `sensorsdb.xml` (keyed on the
EXIF model string) and each group then self-calibrates independently.
FINDINGS measured the numeric priors as a refinement - they steered solved
focals to within 0.005-0.013 of the manufacturer value - while the GROUPING
is what cut zone_1 fragmentation from 9 components to 3. The grouping is
preserved exactly; only the numeric nudge is given up.

DELIVERY
--------
Hard rule 8 (never pass delimited data as .bat arguments): the commands
cross into the workflow as a FILE, one fully-quoted delegated command per
line, which AlignZone.bat feeds to its `:run` subroutine verbatim.
"""

from __future__ import annotations

import logging
import os

from . import camera_registry
from .image_exts import ALL_IMAGE_EXTS

logger = logging.getLogger(__name__)

# Marker written as the first line of a generated command file, so a stale
# file from an older pipeline version is recognisable rather than silently
# replayed.
HEADER = ':: RealityScan prior-group commands - generated by modules/prior_groups.py'


def _path_tolerant(pattern: str) -> str:
    """Re-anchor a family pattern for `-selectImage`, WITHOUT `^` or `$`.

    Two separate constraints:

    1. `camera_registry` patterns are anchored to the bare filename (they
       match against `filename.lower()`), e.g. `^p\\d+c`, while
       `-selectImage` applies its regexp to the image PATH - so a literal
       `^` would only match images at the filesystem root.

    2. `^` is cmd.exe's ESCAPE character. The commands reach AlignZone.bat
       through `for /f` + `call :run %%L`, which re-parses the line, and a
       `^` survives that round trip doubled: a first run emitted
       `-selectImage "(^^|[_\\-.])na168still([_\\-.]|$)"` and RealityScan
       rejected it, failing the whole zone (2026-08-14).

    Both are solved by removing the anchors rather than escaping them.
    Every image sits inside at least one folder, so "start of string" is
    always reachable as a path separator, and every filename carries an
    extension, so "end of string" is always reachable as the `.` delimiter:

        `(^|[_\\-.])tok([_\\-.]|$)`  ->  `([_\\-.])tok([_\\-.])`
        `^p\\d+c`                    ->  `[\\\\/]p\\d+c`
    """
    out = pattern.replace('(^|', '(').replace('|$)', ')')
    if out.startswith('^'):
        out = r'[\\/]' + out[1:]
    if '^' in out or '$' in out:
        raise ValueError(
            f'family pattern {pattern!r} still carries ^ or $ after '
            f'de-anchoring ({out!r}); cmd.exe would mangle it. Add a case '
            'here rather than shipping a regexp the batch layer corrupts.')
    return out


def commands_for_tree(image_root: str) -> list[str]:
    """Delegated commands that group every camera family PRESENT under
    `image_root`, most specific family first.

    Only families with images actually on disk are emitted: issuing a
    `-selectImage` that matches nothing leaves the previous selection in
    place, and the following `-setPrior*Group` would then re-group whatever
    that stale selection happened to be. Each family is therefore preceded
    by its own `-deselectAllImages`.

    Returns an empty list when no known camera family is present - the
    caller decides whether that is fatal.
    """
    present: set[str] = set()
    unknown = 0
    for root, _dirs, files in os.walk(image_root):
        for filename in files:
            if os.path.splitext(filename)[1].lower() not in ALL_IMAGE_EXTS:
                continue
            fam = camera_registry.family(filename)
            if fam is None:
                unknown += 1
            else:
                present.add(fam)

    if unknown:
        logger.warning(
            '%d image(s) under %s match no known camera family; they will '
            'be left ungrouped and RealityScan will calibrate them as one '
            'EXIF-derived group', unknown, image_root)

    commands: list[str] = []
    # Walk the registry order, not `present`, so the most-specific-first
    # guarantee that family() relies on is preserved in the emitted order.
    for spec in camera_registry.families_in_match_order():
        fam = spec['family']
        if fam not in present:
            continue
        camera = camera_registry.CAMERAS[camera_registry.FAMILY_CAMERA[fam]]
        regexp = _path_tolerant(spec['pattern'])
        commands.append('-deselectAllImages')
        commands.append(f'-selectImage "{regexp}"')
        commands.append(f'-setPriorCalibrationGroup {camera.calibration_group}')
        commands.append(f'-setPriorLensGroup {camera.lens_distortion_group}')
    if commands:
        commands.append('-deselectAllImages')
    return commands


def write_command_file(image_root: str, dest: str) -> int:
    """Write the prior-group commands for `image_root` to `dest`.

    Returns the number of camera families grouped (0 when none were found,
    which is the caller's signal that this tree carries no recognised rig).
    """
    commands = commands_for_tree(image_root)
    os.makedirs(os.path.dirname(os.path.abspath(dest)), exist_ok=True)
    with open(dest, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write(HEADER + '\n')
        for command in commands:
            f.write(command + '\n')
    # Four commands per family plus the leading/trailing deselects.
    families = (len(commands) - 1) // 4 if commands else 0
    logger.info('Wrote prior-group commands for %d camera family/families to %s',
                families, dest)
    return families
