"""Generate literal-image calibration/lens selections for RealityScan 2.2.

Registry resolution happens once per basename, most-specific-first. Literal
full paths compose each family's selection with ``union``; no broad regex
can reselect an overlapping family or match a parent directory. The installed
Help documents this form, and docs/rs-reference/02-command-reference.md records
literal-path probes. Command generation is not evidence that groups survived
import/alignment: the per-component prior census remains authoritative.

These commands set grouping only, not focal length or distortion priors.
"""
from __future__ import annotations

import logging
import os

from . import camera_registry
from .image_exts import is_geometry_image

logger = logging.getLogger(__name__)
HEADER = ':: RealityScan prior-group commands - generated by modules/prior_groups.py'


def count_images(image_root: str) -> int:
    """Count recognised image extensions, including unknown camera families."""
    return sum(is_geometry_image(os.path.join(root, name))
               for root, _dirs, files in os.walk(image_root) for name in files)


def _commands_and_family_count(image_root: str) -> tuple[list[str], int]:
    from .realityscan_interface.realityscan_cli import assert_bat_safe

    present: dict[str, list[str]] = {}
    seen: set[str] = set()
    unknown = 0
    for root, dirs, files in os.walk(image_root):
        dirs.sort(key=lambda value: (value.casefold(), value))
        for filename in sorted(files, key=lambda value: (value.casefold(), value)):
            if not is_geometry_image(os.path.join(root, filename)):
                continue
            fam = camera_registry.family(filename)
            if fam is None:
                unknown += 1
                continue
            path = os.path.abspath(os.path.join(root, filename))
            # Lines are replayed through CALL :run, not passed opaquely as data.
            assert_bat_safe([path], 'prior-group selection')
            if any(ord(char) < 32 for char in path):
                raise ValueError(f'Control character in prior-group image path: {path!r}')
            identity = path.replace('\\', '/').casefold()
            if identity in seen:
                raise ValueError(f'Duplicate Windows image identity: {path!r}')
            seen.add(identity)
            present.setdefault(fam, []).append(path)

    if unknown:
        logger.warning('%d image(s) under %s have no registered camera family; '
                       'no groups will be assigned to them. Prior census must '
                       'reject unverified coverage.', unknown, image_root)
    commands: list[str] = []
    for spec in camera_registry.families_in_match_order():
        fam = spec['family']
        if fam not in present:
            continue
        camera = camera_registry.CAMERAS[camera_registry.FAMILY_CAMERA[fam]]
        commands.append('-deselectAllImages')
        for path in present[fam]:
            commands.append(f'-selectImage "{path}" union')
        commands.append(f'-setPriorCalibrationGroup {camera.calibration_group}')
        commands.append(f'-setPriorLensGroup {camera.lens_distortion_group}')
    if commands:
        commands.append('-deselectAllImages')
    return commands, len(present)


def commands_for_tree(image_root: str) -> list[str]:
    """Return disjoint selections assigned by registry basename resolution."""
    return _commands_and_family_count(image_root)[0]


def write_command_file(image_root: str, dest: str) -> int:
    """Write CRLF commands; return family count (not image/command count)."""
    commands, families = _commands_and_family_count(image_root)
    os.makedirs(os.path.dirname(os.path.abspath(dest)), exist_ok=True)
    with open(dest, 'w', encoding='utf-8', newline='\r\n') as stream:
        stream.write(HEADER + '\n')
        for command in commands:
            stream.write(command + '\n')
    logger.info('Wrote prior-group commands for %d camera family/families to %s',
                families, dest)
    return families
