"""Controller boundary: the frontend never launches a pipeline process."""
from collections.abc import Callable
from typing import Protocol

from modules.project_workspace import ProjectDocument


class Controller(Protocol):
    def subscribe(self, callback: Callable[[dict], None]) -> Callable[[], None]: ...
    def settings_schema(self, project: ProjectDocument) -> list[dict]: ...
    def load_project_state(self, project: ProjectDocument) -> list[dict]: ...
    def save_project(self, project: ProjectDocument, path=None): ...
    def adopt_workspace(self, project: ProjectDocument) -> None: ...
    def ensure_cache(self, project: ProjectDocument): ...
    def recover_project(self, project: ProjectDocument) -> dict: ...
    def start(self, project: ProjectDocument, stage: str) -> None: ...
    def stop(self, mode: str = "after_step") -> None: ...
    def scan_inventory(self, project: ProjectDocument) -> None: ...
    def set_inventory_decision(self, project: ProjectDocument, path: str,
                               included: bool, reason: str) -> None: ...
    def confirm_inventory(self, project: ProjectDocument, input_inventory_hash: str,
                          confirmed_by: str) -> None: ...
    def scan_image_quality(self, project: ProjectDocument, tolerances=None) -> None: ...
    def apply_image_culling(self, project: ProjectDocument, assessment_hash: str,
                            excluded_paths: list[str], confirmed_by: str) -> None: ...
    def scan_spatial_review(self, project: ProjectDocument, options=None) -> None: ...
    def apply_spatial_culling(self, project: ProjectDocument, assessment_hash: str,
                              excluded_paths: list[str], confirmed_by: str) -> None: ...
    def confirm_spatial_review(self, project: ProjectDocument, assessment_hash: str,
                                confirmed_by: str) -> None: ...
    def scan_occlusion_masks(self, project: ProjectDocument, options=None) -> None: ...
    def apply_occlusion_masks(self, project: ProjectDocument, assessment_hash: str,
                              confirmed_by: str, *, accepted_block_ids: list[str] | None = None) -> None: ...
    def skip_occlusion_masks(self, project: ProjectDocument, reason: str,
                             confirmed_by: str) -> None: ...


class UnavailableController:
    """Useful for document editing when an execution controller is unavailable."""
    def subscribe(self, callback):
        return lambda: None

    def settings_schema(self, project):
        return []

    def save_project(self, project, path=None):
        return project.save(path)

    def start(self, project, stage):
        raise RuntimeError("No execution controller is connected.")

    def stop(self, mode="after_step"):
        raise RuntimeError("No execution controller is connected.")

    def scan_inventory(self, project):
        raise RuntimeError("No inventory controller is connected.")

    def set_inventory_decision(self, project, path, included, reason):
        raise RuntimeError("No inventory controller is connected.")

    def confirm_inventory(self, project, input_inventory_hash, confirmed_by):
        raise RuntimeError("No inventory controller is connected.")
